//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id_employee { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string name { get; set; }
        public string telephone { get; set; }
        public Nullable<System.DateTime> date_of_employment { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<int> id_position { get; set; }
    
        public virtual department department { get; set; }
        public virtual positions positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
