//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id_order { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_employee { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<System.DateTime> date_of_application { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string home_delivery { get; set; }
        public Nullable<int> quantity_product { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual employee employee { get; set; }
        public virtual product product { get; set; }
    }
}
