//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id_registr { get; set; }
        public string name { get; set; }
        public string PASSWORD_N { get; set; }
        public Nullable<int> role { get; set; }
    }
}
